## global config
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "es"
title                    : "La Cocina de Jamdinho"
title_separator          : "|"
name                     : "jamdinho"
description              : "Blog de recetas caseras y variadas."
url                      : "https://jamdinho.es/"
repository               : "Jamdinho/jamdinho.github.io"
masthead_title           : "La Cocina de Jamdinho"
breadcrumbs              : true
words_per_minute         : 200
comments:
  provider               : "false" # false (default), "disqus", "discourse", "facebook", "staticman", "utterances", "custom"
  disqus:
    shortname            : "jamdinho"
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : "algolia"
algolia:
  application_id         : "G64BH4BS8H"
  index_name             : "lacocinadejamdinho"
  search_only_api_key    : "92e6992d5e7aafdaff895326b25ca2e9"
  powered_by             : true
  files_to_exclude: # exclude files from indexing
    - index.html
    - index.md
    - _drafts/*.md

# SEO Related
google_site_verification : 
bing_site_verification   :
yandex_site_verification :

# Social Sharing
twitter:
  username               : ""
og_image                 : "/assets/images/bio-photo.png"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - https://instagram.com/jamdinho

# Analytics
analytics:
  provider               : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-166625779-1

# Site Author
author:
  name             : "jamdinho"
  avatar           : "/assets/images/bio-photo.png"
  bio              : "Siempre he sido un gran aficionado a la comida, y desde hace unos años también a cocinar."
  location         : "Murcia"
  links:
    - label: "E-mail"
      icon: "fas fa-fw fa-at"
      url: "mailto:contacto.jamdinho@gmail.com"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jamdinho"

# Site Footer
footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jamdinho"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Scripts
after_footer_scripts:
  - /assets/js/go-to-the-top.js

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Madrid

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections # _category dir
# collections:
#  category:
#   output: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true